# mcpkit_apply_sanitizers()
# Appends sanitizer flags to CMAKE_C_FLAGS and CMAKE_C_LINKER_FLAGS so every
# target in the build inherits them. ASan and TSan are mutually exclusive.
function(mcpkit_apply_sanitizers)
    if(MCPKIT_ENABLE_ASAN AND MCPKIT_ENABLE_TSAN)
        message(FATAL_ERROR "MCPKIT_ENABLE_ASAN and MCPKIT_ENABLE_TSAN are mutually exclusive")
    endif()
    if(MCPKIT_ENABLE_ASAN)
        add_compile_options(-fsanitize=address)
        add_link_options(-fsanitize=address)
    endif()
    if(MCPKIT_ENABLE_UBSAN)
        add_compile_options(-fsanitize=undefined)
        add_link_options(-fsanitize=undefined)
    endif()
    if(MCPKIT_ENABLE_TSAN)
        add_compile_options(-fsanitize=thread)
        add_link_options(-fsanitize=thread)
    endif()
endfunction()
