option(MCPKIT_BUILD_TESTS "Build tests" ON)
option(MCPKIT_BUILD_EXAMPLES "Build examples" ON)
option(MCPKIT_BUILD_APPS "Build MCP Apps extension" ON)
option(MCPKIT_BUILD_CLIENT "Build client" ON)
option(MCPKIT_BUILD_SERVER "Build server" ON)
option(MCPKIT_BUILD_HTTP "Build HTTP transport" OFF)
option(MCPKIT_BUILD_SOCKET "Build socket TCP transport" ON)
option(MCPKIT_BUILD_TOOLS "Build CLI tools" ON)
option(MCPKIT_BUILD_FUZZ "Build fuzz targets" OFF)
option(MCPKIT_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(MCPKIT_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(MCPKIT_ENABLE_TSAN "Enable ThreadSanitizer" OFF)
option(MCPKIT_BUILD_SHARED "Build shared library variant" OFF)
